spring.application.name=transaction-back

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/transactions
spring.datasource.username=admin
spring.datasource.password=admin

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8080
